name: Test Datetime API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      id: build-docker-image
      run: docker build -t datetime_api_test .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests in Docker container
        id: run-tests
        run: docker run datetime_api_test pytest
